numba/llvmlite

- llvmlite/ir/builder.py
- llvmlite/ir/instructions.py
- llvmlite/ir/types.py
- llvmlite/ir/values.py
* calling convention attribute in function
* fix GEP addrspace 
* validate actual argument types
* add addrspacecast
* fix PointerType comparision
* tail call
> various enhancement

- README.md
> Mention libedit-dev in the README

- llvmlite/ir/module.py
- llvmlite/ir/types.py
- llvmlite/tests/test_ir.py
(I also removed the redundant else to save a level of indentation).
> Add support for memset, memcpy & memmove in Module.declare_intrinsic.

- docs/source/binding/engine.rst
- ffi/executionengine.cpp
- llvmlite/binding/executionengine.py
- llvmlite/tests/test_binding.py
Helper for Numba issue #1288 (crash with SELinux).
> Add a function to check ability to allocate executable memory.

- llvmlite/ir/values.py
See http://llvm.org/docs/LangRef.html#identifiers.
> Expand _VALID_CHARS to match all LLVM IR identifiers

- CHANGE_LOG
- bench.py
- docs/source/binding/engine.rst
- examples/ll_fpadd.py
- examples/parseasm.py
- examples/sum.py
- ffi/executionengine.cpp
- llvmlite/binding/executionengine.py
- llvmlite/tests/test_binding.py
... with .get_function_address() and .get_global_value_address()
> Replace deprecated .get_pointer_to_global() 

- docs/source/binding/engine.rst
- docs/source/binding/modules.rst
- ffi/core.cpp
- ffi/executionengine.cpp
- ffi/module.cpp
- llvmlite/binding/executionengine.py
- llvmlite/binding/ffi.py
- llvmlite/binding/module.py
- llvmlite/tests/test_binding.py
Todo:
* Validate API with Numba
* Add documentation
> [WIP] Fix #60: provide hooks in to the MCJIT object cache

- docs/source/ir/builder.rst
- docs/source/ir/values.rst
- llvmlite/ir/builder.py
- llvmlite/ir/instructions.py
- llvmlite/ir/values.py
- llvmlite/tests/test_ir.py
Please see the individual commits. Sending them as separate PRs would be too noisy, so I group them in one.
Ex #82.
> Numerous improvements

- ffi/executionengine.cpp
- llvmlite/binding/executionengine.py
The test suite would hang on the object cache tests.
> Avoid a ctypes/libffi issue on Windows 64 and Python 2.6.

- llvmlite/ir/values.py
- llvmlite/tests/test_ir.py
> Fix #125: speed up _escape_string()

- llvmlite/tests/test_binding.py
This allows checking that we didn't unwillingly introduced expected runtime dependencies (such libedit, libcurses...)
> Test DLL dependencies are within a certain expected set

- llvmlite/binding/ffi.py
> Fixed hidden errors on loading libllvmlite.so

- llvmlite/ir/builder.py
- llvmlite/ir/instructions.py
- llvmlite/ir/values.py
- llvmlite/tests/test_ir.py
> Move personality from LandingPadInstr to FunctionAttributes

- ffi/Makefile.freebsd
- ffi/Makefile.linux
- ffi/Makefile.osx
- ffi/build.py
This may avoid questions by users who haven't read the doc very carefully :-)
> Check for LLVM 3.7 at build time

- docs/source/binding/targets.rst
- ffi/targets.cpp
- llvmlite/binding/targets.py
- llvmlite/tests/test_binding.py
See the docstring for explanation.
> Allow emitting verbose assembly

- llvmlite/ir/values.py
(mostly inaccessiblememonly and friends)
> Add missing function attributes

- docs/source/ir/modules.rst
- docs/source/ir/types.rst
- docs/source/ir/values.rst
- llvmlite/ir/instructions.py
- llvmlite/ir/module.py
- llvmlite/ir/types.py
- llvmlite/ir/values.py
- llvmlite/llvmpy/core.py
- llvmlite/tests/test_ir.py
- llvmlite/tests/test_llvmpy.py
This came while trying to add debug information to a toy example. The PR features API improvements, some bug fixes, and better documentation for metadata-related APIs.
> Metadata improvements

- conda-recipes/llvmdev/meta.yaml
Integrate some of the changes in https://github.com/conda-forge/staged-recipes/pull/1482
Those are mostly cosmetic.
> Small improvements to llvmdev recipe

- docs/source/binding/initfini.rst
- llvmlite/binding/initfini.py
- llvmlite/tests/test_binding.py
needed at https://github.com/numba/numba/pull/2149/files#diff-0faf9dcbe850c373d6769c3b1519a29aR194
> Add initializer for asm parser

- llvmlite/ir/values.py
- llvmlite/tests/test_ir.py
Fixes https://github.com/numba/numba/issues/2258
> Fix metadata with long value

- docs/source/ir/builder.rst
- llvmlite/ir/builder.py
- llvmlite/ir/instructions.py
- llvmlite/ir/values.py
- llvmlite/tests/test_ir.py
... to both float binops and call instructions
> Enable fastmath flags 

- buildscripts/incremental/setup_conda_environment.sh
- setup.py
conda-build is having issues when there's a C-extension.
> Fix windows build in conda-build

- setup.py
This avoid the need of workaround of running `python setup.py build` first.
> Fix wheel build with pitrou’s fix.

- docs/source/ir/types.rst
- llvmlite/ir/types.py
- llvmlite/tests/test_binding.py
- llvmlite/tests/test_ir.py
Fixes #267.
A small enhancement to support packed struct.
> Support packed struct

- README.rst
> add Readthedocs badge

- llvmlite/ir/instructions.py
- llvmlite/ir/types.py
- llvmlite/ir/values.py
- llvmlite/tests/test_ir.py
Fixes both constant and non-constant gep
> Fix #274 addrspace in gep

- docs/source/user-guide/ir/ir-builder.rst
> [docs] fix link [skip ci]

- setup.py
> Fix win32 wheel

- docs/source/contributing.rst
[docs] Continuum is now Anaconda
> [docs] Continuum is now Anaconda

- buildscripts/incremental/build.sh
- buildscripts/incremental/setup_conda_environment.sh
- conda-recipes/llvmdev/build.sh
- conda-recipes/llvmdev/meta.yaml
- conda-recipes/llvmlite/bld.bat
- conda-recipes/llvmlite/build.sh
- conda-recipes/llvmlite/meta.yaml
WIP updates for conda build 3.
> Updates for conda build 3

- conda-recipes/llvmdev_manylinux1/bld.bat
- conda-recipes/llvmdev_manylinux1/build.sh
- conda-recipes/llvmdev_manylinux1/meta.yaml
I am reviving the previous llvmdev build recipes for building manylinux1 compatible wheels
> llvmdev recipe for manylinux1 wheels

- docs/source/user-guide/examples/ll_fpadd.py
- ffi/executionengine.cpp
- llvmlite/binding/executionengine.py
- llvmlite/tests/test_binding.py
> Expose support for static constructors/destructors.

- llvmlite/ir/builder.py
- llvmlite/tests/test_ir.py
https://llvm.org/docs/LangRef.html#llvm-ctpop-intrinsic etc
> Add 3 Bit Manipulation Intrinsics

- llvmlite/ir/builder.py
- llvmlite/ir/module.py
- llvmlite/tests/test_ir.py
Some more bit manipulation intrinsics for numba/numba#2824
CC @sklam
> Add cttz & ctlz

- conda-recipes/llvmdev/meta.yaml
- conda-recipes/llvmdev_manylinux1/meta.yaml
> Increment build number.

- CHANGE_LOG
This is a minor patch release that has no code changes. It
includes updates to build recipes for llvmdev (on which llvmlite
relies).
> Update change log for 0.23.1 patch release

- setup.py
Closes #362
Tested on testpypi https://test.pypi.org/project/llvmlite/
> Add long description from readme

- CHANGE_LOG
> Update change log for fixes in 0.24.0rc freeze.

- conda-recipes/llvmdev/meta.yaml
> Fix up broken patch selector

- CHANGE_LOG
> Add further update to change log.

- .travis.yml
- buildscripts/incremental/build.sh
- buildscripts/incremental/setup_conda_environment.sh
- buildscripts/incremental/test.sh
- setup.py
> Add wheel building to TravisCI

- llvmlite/binding/targets.py
> protect against empty features in list

- ffi/build.py
Filter out VS versions that are too old.
> Fix broken win32 py2.7 build.

- buildscripts/incremental/setup_conda_environment.sh
- ffi/CMakeLists.txt
- ffi/build.py
SVML header file used for detecting SVML built into LLVM source
has changed name, update to accommodate.
> Update LLVM 7 config for SVML.

- docs/source/admin-guide/install.rst
The patches don't work unless you supply the "-p1" argument to _patch_.
> Document need for -p1 argument to patch command

- CHANGE_LOG
> Update changelog for 0.29.0

- buildscripts/incremental/setup_conda_environment.sh
> Remove restriction on sphinx version from Anaconda distro

- setup.py
> Fix use of -fPIC flag in wheels

- CHANGE_LOG
> Update release note for v0.30

- llvmlite/ir/module.py
- llvmlite/tests/test_ir.py
> Revert "Revert "LLVM 7 changed memset intrinsic signature, adjust it""

- docs/source/user-guide/binding/execution-engine.rst
> Update docs to not report LLVM 3.8 as latest!

- CHANGE_LOG
> Update change log for 0.31.0

- ffi/build.py
> Update error message in LLVM version check.

- ffi/build.py
Updates the build configuration to allow building on Visual Studio 2017.
> Permit building on Visual Studio 2017

- ffi/build.py
Rebase of #526 after #543 was merged.
> ENH: Better error message

- CHANGE_LOG
> Update changelog for 0.32.0rc1

- CHANGE_LOG
> Update the release date

- docs/source/faqs.rst
- docs/source/index.rst
> Add FAQ entry on LLVM version support.

- CHANGE_LOG
as titled.
like https://github.com/numba/llvmlite/pull/585 but on master branch
> Update changelog for 0.32.1 on master

- buildscripts/manylinux1/build_llvmlite.sh
auditwheel has been updated.
Signed-off-by: Jan Vesely <jano.vesely@gmail.com>
> buildscripts: Unpin wheel

- CHANGE_LOG
> add changelog for 0.34.0

- CHANGE_LOG
> Fix changelog on master

- appveyor.yml
- buildscripts/incremental/setup_conda_environment.cmd
Minimal changes to make appveyor use python3.8
> Fix appveyor

- llvmlite/ir/types.py
- llvmlite/tests/test_ir.py
> Fixes #629: Default to 0 if None is passed as a value for Int32

- ffi/custom_passes.cpp
> Backport llvm refop pass for LLVM 9.

- CHANGE_LOG
> Update changelog for 0.35.0rc1

- CHANGE_LOG
> Update CHANGE_LOG for 0.35.0rc2

- ffi/passmanagers.cpp
- llvmlite/binding/passmanagers.py
- llvmlite/ir/builder.py
- llvmlite/ir/instructions.py
- llvmlite/tests/test_binding.py
- llvmlite/tests/test_ir.py
> Add support for general attrs on call and loop-rotate pass

- CHANGE_LOG
> Update changelog for 0.35.0rc3

- CHANGE_LOG
- ffi/passmanagers.cpp
- llvmlite/binding/passmanagers.py
- llvmlite/ir/builder.py
- llvmlite/ir/instructions.py
- llvmlite/tests/test_binding.py
- llvmlite/tests/test_ir.py
cherry picked PRs and ~updated changelog~ need to cherry pick changelog PR https://github.com/numba/llvmlite/pull/651
> Preparing 0.35.0rc3

- CHANGE_LOG
> Update changelog for 0.35.0 final

- docs/source/user-guide/binding/index.rst
- docs/source/user-guide/binding/pass_timings.rst
- ffi/passmanagers.cpp
- llvmlite/binding/passmanagers.py
- llvmlite/tests/test_binding.py
```python
llvm.set_time_passes(True)
<compile something>
report = llvm.report_and_reset_timings() # return str
llvm.set_time_passes(False)
```
> Expose pass timings

- README.rst
> fixup azure badge to point at master branch

- docs/source/user-guide/binding/index.rst
- docs/source/user-guide/binding/misc.rst
- llvmlite/binding/ffi.py
- llvmlite/tests/test_binding.py
> Callback to track when the llvm lock is acquired and released

- CHANGE_LOG
> Release Notes v0.36.0RC1

- CHANGE_LOG
> Update changelog for 0.36.0 final 

- CHANGE_LOG
Same as https://github.com/numba/llvmlite/pull/706 but for main
> Update changelog for 0.36.0 final release date

- docs/environment.yml
- readthedocs.yml
> Use conda for readthedocs with Python 3.9

- buildscripts/azure/azure-windows.yml
- buildscripts/incremental/setup_conda_environment.cmd
- buildscripts/incremental/setup_conda_environment.sh
As it is now passing everywhere else, we upgrade public CI now too.
> bump llvmdev to 11

- CHANGE_LOG
- docs/environment.yml
> Changelog 0.37.0

- CHANGE_LOG
> adding PRs specific to the RC2 release

- README.rst
Cleanup some cruft in the README
> Fixup readme

- CHANGE_LOG
- README.rst
- azure-pipelines.yml
- conda-recipes/llvmlite/meta.yaml
- docs/source/contributing.rst
- setup.py
> More cherrypicked patches for release 0.37.0rc2

- CHANGE_LOG
> Update CHANGE_LOG for 0.37.0

- CHANGE_LOG
> Release 0.37.0 final patches

- llvmlite/tests/test_binding.py
This makes the tests for the RISCV target ABI name only execute if
the linked LLVM supports compilation (host or cross) to the RISCV
target.
> Make tests that require cross compilation to RISCV optional.

- CHANGE_LOG
> adding changelog for 0.38.0 RC1

- buildscripts/manylinux2014/configure_conda.sh
- conda-recipes/llvmdev_manylinux2014/meta.yaml
> manylinux2014 aarch64 wheels with system compilers

- CHANGE_LOG
> Update CHANGE_LOG for 0.38.0

- CHANGE_LOG
> cherry pick final changelog from #809

- .github/ISSUE_TEMPLATE/bug_report.md
- README.rst
- docs/source/admin-guide/install.rst
> update local references

- llvmlite/ir/builder.py
- llvmlite/ir/instructions.py
- llvmlite/tests/test_ir.py
As title.
Closes https://github.com/numba/llvmlite/issues/798
Modification of https://github.com/numba/llvmlite/pull/709
> Add flag handling to more instructions.

- docs/source/user-guide/ir/values.rst
- llvmlite/ir/values.py
- llvmlite/tests/test_binding.py
- llvmlite/tests/test_ir.py
> Add section to globals

- setup.py
> remove uppper limit on Python requires

- .clang-format
- azure-pipelines.yml
- buildscripts/azure/azure-linux-macos.yml
- docs/source/contributing.rst
- ffi/assembly.cpp
- ffi/bitcode.cpp
- ffi/core.cpp
- ffi/core.h
- ffi/custom_passes.cpp
- ffi/dylib.cpp
- ffi/executionengine.cpp
- ffi/initfini.cpp
- ffi/linker.cpp
- ffi/module.cpp
- ffi/object_file.cpp
- ffi/passmanagers.cpp
- ffi/targets.cpp
- ffi/transforms.cpp
- ffi/value.cpp
Add formatting Azure pipeline and reformat all existing C++ code
> Format C++ code

- azure-pipelines.yml
Update Windows and OSX CI images.
> Backport #786 for 0.38.1

- CHANGE_LOG
> Changelog for 0.38.1

- CHANGE_LOG
> Cherry-Pick: #842 --> `main` :Changelog for 0.38.1

- docs/source/admin-guide/install.rst
> adding the llvm_11_consecutive_registers.patch

- .github/ISSUE_TEMPLATE/first_rc_checklist.md
- .github/ISSUE_TEMPLATE/sub_rc_checklist.md
> adding rc and final release checklist templates

- CHANGE_LOG
> Update CHANGE_LOG for 0.39.0

- CHANGE_LOG
- docs/source/conf.py
Also, setting the sphinx language to "en" for sphinx to stop warning
> Update changelog for 0.39.0 release

- CHANGE_LOG
> Update release date for 0.39.0 release.

- CHANGE_LOG
- docs/source/conf.py
contains changelog and sphinx conf changes only
> Cherry pick for 0.39 release

- CHANGE_LOG
> Update change log for 0.39.1

- azure-pipelines.yml
- buildscripts/azure/azure-windows.yml
- buildscripts/incremental/setup_conda_environment.cmd
- buildscripts/incremental/setup_conda_environment.sh
Side-note: wheel build has not been updated yet to llvm14
> Setup AzureCI to use py311 and llvm14 

- buildscripts/azure/azure-windows.yml
we missed this config in the last PR.
> Fix AzureCI not using llvm14 on windows

- conda-recipes/llvmdev/bld.bat
- conda-recipes/llvmdev/meta.yaml
> Disable zlib for LLVM on Windows

- conda-recipes/llvmlite/meta.yaml
Relates https://github.com/numba/llvmlite/pull/935
> Bump llvmdev build number to include the nozlib change for windows

- CHANGE_LOG
> Update CHANGE_LOG for 0.40.0 final.

- CHANGE_LOG
- conda-recipes/llvmdev/bld.bat
- conda-recipes/llvmdev/meta.yaml
- conda-recipes/llvmlite/meta.yaml
Include PR:
- https://github.com/numba/llvmlite/pull/935
- https://github.com/numba/llvmlite/pull/939
- https://github.com/numba/llvmlite/pull/940
> Cherrypicks for release 0.40.0 final

- .github/workflows/release.yml
- buildscripts/github/config.toml
- buildscripts/github/install_llvmdev.ps1
- buildscripts/github/install_llvmdev.sh
Build a new GitHub Action to build wheels for llvmlite
> Create GitHub Action for llvmlite release

- README.rst
> fixup LLVM versions in version compat table

- CHANGE_LOG
> update release notes for 0.41.0

- ffi/Makefile.freebsd
> Fix FreeBsd build

- .readthedocs.yaml
- CHANGE_LOG
- docs/environment.yml
- docs/source/conf.py
- ffi/Makefile.freebsd
- readthedocs.yml
- setup.py
Cherry-picks and changelog updates for 0.41.0 FINAL.
> Release 0.41.0 FINAL

- CHANGE_LOG
> Update changelog on main for 0.41.0

- README.rst
- docs/source/user-guide/ir/ir-builder.rst
> fix typos found by codespell

- CHANGE_LOG
> Release Notes 0.41.1 for main

- .github/ISSUE_TEMPLATE/first_rc_checklist.md
- .github/ISSUE_TEMPLATE/sub_rc_checklist.md
> update release checklists post 0.41.1

- conda-recipes/llvmlite/meta.yaml
> Fix conda-recipe syntax errors from #1012

- CHANGE_LOG
> Update CHANGE_LOG for 0.42.0 final.

- CHANGE_LOG
- cherrypick https://github.com/numba/llvmlite/pull/1029
> v0.42 Post release 

- .github/ISSUE_TEMPLATE/first_rc_checklist.md
> Add conda-forge pre-tag testing to release checklist

- ffi/Makefile.netbsd
- ffi/build.py
> Add NetBSD support.

- azure-pipelines.yml
- buildscripts/azure/azure-linux-macos.yml
- buildscripts/incremental/build.sh
- llvmlite/ir/builder.py
- llvmlite/tests/test_ir.py
As titled, this PR cherry-picks #1097 and #1098 from `main` onto the release branch for `0.44.0rc2`.
> Cherry-picks for `0.44.0rc2`

- CHANGE_LOG
> Update changelog for v0.44.0rc2

- buildscripts/github/llvmdev_evaluate.py
> fix flake8 issues

- .github/workflows/llvmlite_win-64_conda_builder.yml
> enable running workflow as part of pull-request

- .github/workflows/pre-commit.yml
> adding pre-commit workflow

- renovate.json
context: https://github.com/numba/llvmlite/issues/1155
See also:
* https://docs.renovatebot.com/presets-helpers/#helperspingithubactiondigeststosemver
* https://github.com/renovatebot/renovate/discussions/21901
> Enable Github Action pinning via renovate

- ffi/CMakeLists.txt
Fixes: build issues on Azure like these: https://dev.azure.com/numba/numba/_build/results?buildId=18653&view=logs&jobId=9dac8226-a5f6-5250-2324-4bdf29bd2779&j=9dac8226-a5f6-5250-2324-4bdf29bd2779&t=f5f04a88-f179-58ce-90e8-cad4e3660936
> bump min CMake

- azure-pipelines.yml
> remove singular clang-format check based on ubuntu/apt

- .github/workflows/llvmlite_osx-arm64_conda_builder.yml
this PR adds llvmlite conda package build and test workflow for osx-arm64
> gha/add llvmlite osx-arm64 conda builder

- docs/source/user-guide/index.rst
- docs/source/user-guide/llvm20.rst
> adding llvm20 docs
