numba/llvmlite

README.md

Response to issue [#27](https://github.com/numba/llvmlite/issues/27).
I verified that you can build on Ubuntu 14.04 LTS following posted instructions, as long as you use the Debian `llvm-3.5-dev` and not the Ubuntu package. I suggest a note will be added to the readme.

Readme: added Ubuntu build warning.

---

setup.py

install 'llvmlite' with pip will cause this error
error: option --single-version-externally-managed not recognized
this patch fix this problem

Fix 'pip' install problem

---

llvmlite/ir/module.py
llvmlite/tests/test_ir.py

The accessor allows querying the globals mapping without directly accessing the
class's attributes. Discussed in issue #39 
Note: the C++ API has getFunction and getGlobalVariable, which do the type checking in addition to querying the symbol table. It's possible to redo the API that way, if this is deemed preferable.

Add .get_global() accessor to ir.Module

---

llvmlite/ir/module.py
llvmlite/tests/test_ir.py

global_values is more consistent with the method's actual behavior. Discussed in #41

Rename Module.global_variables to Module.global_values and add tests.

---

conda-recipes/llvmlite-jenkins/bld.bat

The -S flag appears to prevent Python from finding any of the packages in the `_build` environment on Python 3.3. on Windows.

Attempt to fix build on Windows Python 3.3

---

llvmlite/binding/common.py
llvmlite/tests/test_ir.py

With certain constant i8 values, LLVM will generate LLVM IR that contain invalid characters for UTF8.  LLVM is probably using latin1.  Although, I can't find any documentation about character encoding for LLVM IR.
This PR contains a test that fails when using UTF8 encoding.  I have verified that this patch works with Numba on OSX.

Use latin1 encoding instead of UTF8

---

ffi/module.cpp
llvmlite/tests/test_binding.py

... and reverting afterwards.
* Fix #80
* Without the fix, LLVM will fail with an assertion.

Always change to C locale before printing a module

---

docs/source/ir/builder.rst
llvmlite/ir/builder.py
llvmlite/tests/test_ir.py

This attribute may be set by the frontend once prior to emitting
many LLVM IR instructions corresponding to a single source-level
entity (such as an AST node).

Add IRBuilder.debug_metadata attribute

---

llvmlite/binding/ffi.py

Fixes (AFAIK) numba/numba#1177
With this PR, we simply need to copy llvmlite.dll to the frozen executable directory and it works.

try to find .dll in local directory to fix support for frozen apps

---

ffi/executionengine.cpp
llvmlite/binding/executionengine.py

Add the OProfile JIT event listener to allow the JIT'ed code
to be analyzed with a hardware profiler on Linux.
To enable this code:
- enable LLVM for OProfile JIT events (-DLLVM_USE_OPROFILE=ON)
- define USE_OPROFILE_JITEVENTS when compiling llvmlite
- define environment variable ENABLE_JITPROFILING
- LD_LIBRARY_PATH may need to point to the directory containing
libopagent.so (/usr/lib/oprofile)
Tested with LLVM 3.6
Annotating assembly works (with opannotate), but I think debug information will be needed to annotate source (see issue #10 )

Support profiing with OProfile

---

.travis.yml

This avoids having to install and activate a gcc backport.
See https://docs.travis-ci.com/user/trusty-ci-environment/

Adapt Travis config for Trusty beta

---

llvmlite/ir/types.py
llvmlite/tests/test_ir.py

If an identified struct type from a context that is not global
is used anywhere in the type that is passed to
get_abi_{size,alignment}, the generated LLVM IR is invalid.
This pull request adds a `context` argument, which allows
to specify a non-global context explicitly.

Let Type.get_abi_{size,alignment} not choke on identified types.

---

docs/source/install/index.rst

Patch attempts to add clarity to the instructions surrounding the
use of LLVM_CONFIG for installations with LLVM in a non-standard
location.

Minor documentation fix for LLVM_CONFIG instructions.

---

ffi/Makefile.linux
ffi/build.py

The workarounds we used to have for bugs in llvm-config don't seem necessary anymore.

Fix #121: simplify build process on Unix

---

examples/llvmir.py

using `builder.constant` instead of `ll.constant` resulting in 'IRBuilder' object has no attribute 'Constant' error.

Correct constant in llvmir.py example

---

MANIFEST.in

Having stray `CMakeCache.txt` files cause trouble when building on windows. Removing them is easier than trying to understand cmake :)
Fix #140

MAINT: ensure no CMakeCache.txt file is included in sdist.

---

ffi/Makefile.linux

Background: Clang & LLVM's binary releases are now built with Clang itself,
which means we have to compile llvmlite with Clang when compiling vs. a binary
release taken from http://llvm.org/releases/
However, in that case Clang looks for the Gold plugin for LTO, which is not
built into the binaries by default. So this makes building llvmlite on your own
very cumbersome.
Alternatively we can just not use LTO. This change permits overriding the LTO
setting from the environment when needed.

Allow overriding flto in ffi builds on Linux.

---

llvmlite/ir/_utils.py
llvmlite/ir/module.py
llvmlite/ir/values.py

LLVM has three scopes: a context-level scope that contains named
types (which have a %name); a module-level scope that contains named
globals (which have a @name); and a function-level scope that
contains instructions (which have a %name). Names in all three scopes
cannot conflict: either the sigil is different, or the sigil is
the same but the names appear in disjoint lexical positions.
So, remove all the logic responsible for handling nested scopes,
since it is pointless.

Implement LLVM scoping correctly

---

llvmlite/binding/targets.py
llvmlite/tests/test_binding.py

There was no check of self._owned, which could lead to a segfault
during the straightforward use of the API. It is essentially never
useful to have a reference to TargetData owned by the pass manager,
so just always make a copy instead.

Always copy TargetData when adding to a pass manager

---

setup.py

It's a bit annoying to remove all temporary files before building from scratch. This PR adds a simple clean command to fix this.

Clean command added to setup.py

---

ffi/targets.cpp
llvmlite/binding/targets.py

`TargetMachine::getDataLayout()` is going away in LLVM 3.8. `TargetMachine::createDataLayout()` returns `DataLayout` by value, so I'm wrapping it in `new`.

Remove deprecated uses of TargetMachine::getDataLayout()

---

llvmlite/ir/values.py
llvmlite/tests/test_ir.py

Before, it was emitted as `!0 = { zeroinitializer }`.

Properly emit IR for metadata null

---

docs/source/binding/initfini.rst
ffi/initfini.cpp
llvmlite/binding/initfini.py
llvmlite/tests/test_binding.py

Without this, it's not possible to emit assembly or code directly using llvmlite, which severely limits its usefulness; one would have to resort to executing llc, which means search path problems, Windows compatibility problems, etc. So, the resulting enlargement of the package is worth it.

Expose initialize_all_{targets,asmprinters}

---

docs/source/binding/passmanager.rst
ffi/passmanagers.cpp
llvmlite/binding/passmanagers.py
llvmlite/tests/test_binding.py

This is just a bunch of passes our compiler needs, since exposing them all is a lot of work for unclear benefit (indeed, exposing passes no one needs in practice just adds maintenance burden, as they are removed, renamed, etc in newer LLVM versions). However, this list should nevertheless be generally useful.

Expose functions to create individual passes

---

llvmlite/ir/values.py
llvmlite/tests/test_binding.py

IR spec requires GV with non-external linkage (linkage other than external and extern_weak) to have a initializer.  Otherwise, `parse_assembly` will reject the IR as invalid.  This patch makes `undef` the default initializer for these cases.
In details: if the the `.initializer` is `None` and linkage is non-external, emit `undef` to the IR.

Default initializer for global variable with non external linkage

---

docs/source/ir/builder.rst
llvmlite/ir/builder.py
llvmlite/ir/instructions.py
llvmlite/tests/test_ir.py

Currently the way to add fast-math flags to instructions in
llvmlite is to mutate Instruction.opname for every individual one
to append flags, e.g. 'add nsw nuw' or 'frem fast'. However,
before this commit CompareInstr used the class attribute
self.OPNAME, defeating this method.

Allow emission of fast-math fcmp instructions

---

docs/source/ir/values.rst
llvmlite/ir/_utils.py
llvmlite/ir/instructions.py
llvmlite/ir/values.py
llvmlite/tests/test_ir.py

This was brought in around LLVM 3.7 and is only currently used for debug information.
I feel like the `leading_comma` parameter, when it exists, should default to `False`, hence a bit of churn below.

Allow adding metadata to functions

---

ffi/passmanagers.cpp

The default LLVM diagnostic handler always prints some optimization remarks
(see http://lists.llvm.org/pipermail/llvm-dev/2016-July/102252.html).
Work around it by setting our own diagnostic handler during optimization.

Suppress optimization remarks

---

llvmlite/ir/values.py
llvmlite/tests/test_ir.py

Also, allow all printable ASCII characters in IR string literals,
including metadata strings and character array initializers.

Escape the contents of metadata strings

---

llvmlite/ir/module.py
llvmlite/ir/values.py
llvmlite/tests/test_ir.py

This is pretty much enough to do emission of debug info of any complexity, e.g. see https://github.com/m-labs/artiq/blob/ce30045dd4b85d20bd9ac2aa72ca8f7481cc6a43/artiq/compiler/transforms/llvm_ir_generator.py#L42-L127. It is in principle possible to model individual DINodes within llvmlite, but doesn't really make a lot of sense and is prone to breakage after upgrading LLVM.

Add support for debug information

---

llvmlite/tests/test_binding.py

As mentioned in [issue #208](https://github.com/numba/llvmlite/issues/208), this unit tests forbids valid library file names, like `libname.so.3.8` and `libname.so.3.8.1`.  This modifies the regular expression to allowed those sorts of file names.

Allow TestDependencies to match other valid library file names

---

ffi/CMakeLists.txt
ffi/Makefile.freebsd
ffi/Makefile.linux
ffi/Makefile.osx
ffi/object_file.cpp
llvmlite/binding/__init__.py
llvmlite/binding/executionengine.py
llvmlite/binding/ffi.py
llvmlite/binding/object_file.py
llvmlite/tests/test_binding.py

It misses the symbols API, but that's still a start!

Add partial LLVM bindings for object::ObjectFile

---

llvmlite/binding/linker.py

We should let user run the verification instead of doing it in linkage.

Remove unnecessary verify in module linkage

---

docs/source/ir/builder.rst
llvmlite/ir/builder.py
llvmlite/ir/instructions.py
llvmlite/tests/test_ir.py

Add three helper functions in the builder:
- asm: create a call to an inline assembler object
- store_reg: store an LLVM value into a specific register
- load_reg: set an LLVM value as the value inside a register
The previous pull request was non-sense since there already is an InlineAsm instruction...

Add InlineAsm helpers in the builder

---

ffi/build.py
ffi/targets.cpp
llvmlite/binding/targets.py
llvmlite/tests/test_binding.py

RelocMode is now Optional<RelocMode>, where None has the same meaning
as Default used to.
Data layout is no longer ever optional, so there is no need in
explicitly adding it anywhere; those APIs were removed in LLVM.

Update for changes in LLVM 3.9

---

setup.py

`python setup.py build` in a `Python2.7` environment without `enum34` installed fails
Steps to reproduce:
```
conda create -n llvm_27 python=2.7 -y
source activate llvm_27
python setup.py build
```
Error:
```
Traceback (most recent call last):
File "setup.py", line 24, in <module>
from llvmlite.utils import get_library_files
File "...", line 6, in <module>
raise ImportError("could not find the 'enum' module; please install "
ImportError: could not find the 'enum' module; please install it using e.g. 'pip install enum34'
```
Moving the `import`s inside the `distutils.command`s they're used in makes sure the import doesn't happen until after the packages in `install_requires` have been installed.
Fixes https://github.com/numba/llvmlite/issues/194

Fix setup.py for Python2.7

---

llvmlite/ir/types.py
llvmlite/tests/test_ir.py

All of the ir.Types are not hashable in Python 3 because they define their own ``__eq__`` methods. It would be nice for types to be hashable so they could be used in sets or as keys to a dict. This fix is also necessary for correctness under Python 2:
```python
In [12]: a, b = ir.VoidType(), ir.VoidType()
In [13]: a == b
Out[13]: True
In [14]: hash(a) == hash(b)
Out[14]: False
```
Overriding ``__hash__`` on the ``Type`` class doesn't work because
> A class that overrides __eq__() and does not define __hash__() will have its __hash__() implicitly set to None. When the __hash__() method of a class is None, instances of the class will raise an appropriate TypeError when a program attempts to retrieve their hash value, and will also be correctly identified as unhashable when checking …

Add __hash__ to all IR types

---

conda-recipes/llvmlite/build.sh
conda-recipes/llvmlite/run_test.py
ffi/Makefile.linux
ffi/build.py
llvmlite/tests/test_binding.py

(Fix #249)
Only enable it for distribution build in the conda recipe.
User can still override with LLVMLITE_CXX_STATIC_LINK.

Disable static linking of libstdc++ by default.

---

setup.py

Previously, it has to depend on user running `build_ext —inplace` before doing `bdist_wheel`.
Here we patch the `bdist_wheel` command ~~~to  include the library files, a pattern used for other command as well.~~~ to detect that the library files do exist.
To build wheels, run
```bash
python setup.py build      
python setup.py bdist_wheel
```

Fix wheel build

---

llvmlite/ir/module.py
llvmlite/tests/test_ir.py

Fix the behavior of module.get_global to keep consistency with the document.
Document says: 
> Get the global value (a GlobalValue) with the given name. KeyError is raised if it doesn’t exist.
But actually `dict.get` will never raise an `KeyError`. `OrderedDict` is a subclass of `dict`.
See:
https://docs.python.org/2/library/stdtypes.html#dict.get
https://docs.python.org/3/library/stdtypes.html#dict.get

Fix the behavior of module.get_global

---

conda-recipes/llvmlite/meta.yaml

CFLAGS, CXXFLAGS and PY_VCRUNTIME_REDIST need to be passed
through to conda-build so that 32 bit cross compilation works.

Add variables to pass through when doing conda-build

---

conda-recipes/llvmdev/meta.yaml

Add pass through gcc flags for llvmdev

---

setup.py

Having `ext_stub` somehow break conda-build but it is needed for wheel build.  The fix is to hide it when we are not building wheels.

Fix building with conda-build on win32

---

README.rst
buildscripts/incremental/setup_conda_environment.cmd
buildscripts/incremental/setup_conda_environment.sh
conda-recipes/llvmdev/meta.yaml
conda-recipes/llvmlite/meta.yaml
docs/source/admin-guide/install.rst
docs/source/conf.py
docs/source/user-guide/binding/execution-engine.rst
docs/source/user-guide/ir/index.rst
ffi/build.py
ffi/executionengine.cpp
ffi/value.cpp
llvmlite/binding/executionengine.py
llvmlite/binding/value.py
llvmlite/tests/test_binding.py

Based on #306 
This updates llvmlite for the changes in LLVM 5:
* Fix C-API get attribute usage.
* Remove the deprecated get_pointer_to_function since it behavior is unexpected.

Fixes for LLVM5

---

README.rst
buildscripts/incremental/setup_conda_environment.cmd
buildscripts/incremental/setup_conda_environment.sh
conda-recipes/llvmdev/meta.yaml
conda-recipes/llvmlite/meta.yaml
docs/source/admin-guide/install.rst
docs/source/conf.py
docs/source/user-guide/ir/index.rst
ffi/build.py

This patch bumps the build recipes, documentation and source with
view of moving to support LLVM 5.0 by default.

Working towards LLVM 5.0 support.

---

conda-recipes/llvmdev/build.sh

This removes temporary code needed to make linux64->linux32 cross
compilation work, the fix is now upstream so this can be removed.

Remove temporary code to make cross compilation work.

---

llvmlite/binding/ffi.py

~~~(don't merge this until 0.21.0 is released.)~~~
Various race-condition issues had been revealed in the numba testsuite and hacks were made to temporarily workaround the issues.  This patch provides a proper solution to the threadsafety problem by employing a lock on all LLVM C-API calls.  
LLVM uses a LLVMContext to store shared data.  By isolating LLVMContext and disallowing sharing of LLVMContext among threads, threadsafety issues could be avoided.  However, the current llvmlite API does not expose LLVMContext creation and the APIs assume a single global context.  So, we must ensure that the LLVM APIs will not be concurrently used.  By using a global lock for all LLVM API, it can keep the llvmlite API simple and safe.  Later when we discover certain LLVM APIs to be threadsafe, we can …

Ensuring threadsafety in concurrent usage of LLVM C-API

---

llvmlite/ir/values.py
llvmlite/tests/test_ir.py

... except the Swift ones since those seem useless.

Add all function/return value attributes from LLVM 3.9

---

conda-recipes/intel-svml.patch
conda-recipes/llvmdev/meta.yaml
conda-recipes/llvmdev_manylinux1/meta.yaml

This patch allows to enable SVML in LLVM correctly on all the platforms and provides a way to choose faster functions by loosing some accuracy via fastmath=True argument in Numba
Credit to @dvnagorny for the LLVM patch

Enable Intel SVML-enabled auto-vectorization for all the transcendentals

---

conda-recipes/llvmdev/cfg_test.ll
conda-recipes/llvmdev/meta.yaml
conda-recipes/llvmdev/test_cfg_dot.py
conda-recipes/llvmdev_manylinux1/meta.yaml
conda-recipes/twine_cfg_undefined_behavior.patch

This adds a patch to LLVM source code to fix an undefined behavior bug.  A new test is added for the llvmdev package to verify the patch worked.  Note, the patched code will only affect branch weight printing at WriteCFG during CFG DOT file generation.

Fix undefined behavior bug due to Twine usage in LLVM

---

llvmlite/ir/builder.py
llvmlite/ir/instructions.py
llvmlite/tests/test_ir.py

The `fence` instructions are useful for shared-memory scenarios on weak-memory-model machines like PowerPC and ARM.
More specifically, it is necessary to use fences to render safe Numba's reference count increment/decrement.
We add here an `llvmlite.ir.instructions.Fence` instruction and a method `IRBuilder.fence(targetscope, ordering, name='')`.
The legal values of `targetscope` are `None`, `"singlethread"` and other target-specific supported values.
The legal values of `ordering` are `"acquire"`, `"release"`, `"acq_rel"` and `"seq_cst"`.

Add support for LLVM fence instruction

---

conda-recipes/llvmdev/meta.yaml
conda-recipes/llvmlite/meta.yaml
ffi/Makefile.linux
ffi/Makefile.osx

This adds a selector such that windows does not use Anaconda
defined compilers which have a dependency on vc9.

Fix llvmdev build recipe.

---

CHANGE_LOG
ffi/CMakeLists.txt
ffi/build.py
ffi/targets.cpp
llvmlite/binding/targets.py

This adds detection of SVML support in a LLVM build at compile
time. This is then exposed such that it can be queried at run time
from Python in a manner that is suitable for use in the SVML
initialisation and detection sequence.
Closes #3006
Fixes #2998

Add SVML detection and a function to declare support.

---

llvmlite/tests/test_ir.py

With `python -c "import re; print(re.sub(r'\s+',r'\s*','      here are  some   words'))"`
Python 2.7 and 3.6 give:
```
\s*here\s*are\s*some\s*words
```
While Python 3.7 gives:
```
Traceback (most recent call last):
File "/opt/conda/envs/py37/lib/python3.7/sre_parse.py", line 1021, in parse_template
this = chr(ESCAPES[this][1])
KeyError: '\\s'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/opt/conda/envs/py37/lib/python3.7/re.py", line 192, in sub
return _compile(pattern, flags).sub(repl, string, count)
File "/opt/conda/envs/py37/lib/python3.7/re.py", line 309, in _subx
template = _compile_repl(template, pattern)
File "/opt/conda/envs/py37/lib/python3.7/re.py", line 300, in _compile_repl …
```

Python 3.7 compat: Properly escape repl in re.sub

---

conda-recipes/llvmlite/bld.bat
conda-recipes/llvmlite/build.sh
conda-recipes/llvmlite/meta.yaml

Newer versions of Conda Build are more stricter about the build/host split.

Recipe fixes for Conda Build 3

---

llvmlite/binding/ffi.py

This can happen if it is called at interpreter shutdown.
Partial fix to #350 (I didn't try to fix any other `__del__` methods).

Guard against close being None in ObjectRef.__del__

---

conda-recipes/llvmdev/meta.yaml

This adds in the ability to build from the LLVM 6.0.1 releases (yet
to formally ship). This release is needed for PPC64LE support and
is masked off as such.

LLVM 6.0.1 build based on RC and fixes for PPC64LE

---

docs/source/user-guide/ir/ir-builder.rst

As mentioned in #298, the docs give wrong information about the `extractvalue` instruction (compare with [the LLVM IR Ref](https://llvm.org/docs/LangRef.html#extractvalue-instruction)).

Fix docs for the extractvalue instr

---

docs/source/user-guide/binding/index.rst
docs/source/user-guide/binding/target-information.rst
docs/source/user-guide/binding/type-references.rst
docs/source/user-guide/binding/value-references.rst
ffi/value.cpp
llvmlite/binding/value.py
llvmlite/ir/types.py
llvmlite/tests/test_binding.py

The `LLVMPY_TypeRef` class is a completely opaque type right now. This adds a thin wrapper which prints the LLVM IR representation of the LLVM Type.
If this change is ok, I'll adjust the documentation, too.
I have one further PR prepared which allows extracting `TypeRef`s from a `ModuleRef`, similar to the `get_function` and `functions`. I'd like to wait for the feedback on this PR first, though.
My envisioned use case is making the interop with external modules easier. Let say I've compiled some C code to a `c.ll` file. I'd like to use functions and structs defined there from a module created with `llvmlite`. Right now I'd have to manually forward declare everything. With these changes I can pretty much automate everything.

Add printing to the bound llvm type

---

ffi/build.py

I needed to use VS2017 to compile llvmlite so this change was needed to use the right generator.
@stuartarchibald, @sklam

Read CMAKE_GENERATOR which conda-build sets

---

docs/source/user-guide/ir/ir-builder.rst

IRBuilder documentation mentions IRBuilder.sadd_with_overflow two times. But should IRBuilder.ssub_with_overflow the second time.

Fix typo in irbuilder documentation

---

llvmlite/binding/ffi.py

On older Pythons (<3.4) the shutdown sequence sets globals etc
to None to help gc. This means that the calling of a global as
part of `__del__` as occurs in `ffi::ObjectRef` leads to error
messages like:
`Exception TypeError: "'NoneType' object is not callable" in...`
Using the already existing shutdown detection mechanism in the
`__del__` it's possible to avoid calling the global and as a
result stops these message/calling None. The LLVM object will
leak either way, at least this way is leaks quietly.
Fixes #350
Fixes numba/numba#2818

Add shutdown detection to ObjectRef __del__ method.

---

conda-recipes/llvmlite/meta.yaml

Don't assume that make is part of the build container

conda recipe: add make as build dep

---

conda-recipes/llvmdev/meta.yaml

As title, required as toolchain has incompatible conda packages.

Use native cmake on armv7l

---

llvmlite/ir/values.py
llvmlite/tests/test_ir.py

Constant pointer objects provide a `gep` method. Unfortunately, it doesn't work on them, since it expects an attribute `addrspace` to be present.
This PR adds a `addrspace` property to `Constant` class and a test to check if it works properly.

Fix gep method call on Constant objects

---

docs/source/user-guide/binding/target-information.rst
ffi/targets.cpp
llvmlite/binding/targets.py
llvmlite/tests/test_binding.py

`LLVMOffsetOfElement` is useful when working with structs from a compiled module. This PR exposes this functionality in python.

Add get_element_offset to TargetData

---

conda-recipes/llvmdev/build.sh

This adds another thread for LLVM building, RPi3B+ can handle it.

Add another thread for RPi builds.

---

ffi/build.py

This needs to be a raw string literal so that Python won't try to interpret `\d`.

Fix "SyntaxWarning: invalid escape sequence \d"

---

docs/source/user-guide/ir/values.rst
llvmlite/ir/_utils.py
llvmlite/ir/instructions.py
llvmlite/ir/values.py
llvmlite/tests/test_ir.py

#420 got me looking: the `replace_usage` doesn't have any documentation. Also there seem to be confusing behavior caused by instruction representation caching. 
This PR adds a couple of tests and a short description of `replace_usage` to the docs.

Normalize replace_* behaviour and add docs

---

llvmlite/ir/values.py
llvmlite/tests/test_ir.py

Pickling of the `ir.Function` instances was broken due to interaction of optional arguments in `AttributeSet` constructor and it's children. This PR also adds a couple of tests for this.

Fix pickling of IR functions and add tests

---

llvmlite/ir/builder.py
llvmlite/tests/test_ir.py

Fixes #453.
Also the long label names are not useful anyway.
Label names will now be truncated when too long.  The cutoff point is picked arbitrarily.

Truncate long label names when adding label suffix.

---

llvmlite/ir/instructions.py

From https://releases.llvm.org/7.0.0/docs/LangRef.html#fast-math-flags

Add missing fastmath flags from LLVM 7

---

llvmlite/ir/module.py
llvmlite/tests/test_ir.py

Since LLVM 7 memset doesn't take an alignment as a third parameter and respects first argument's alignment instead, see https://releases.llvm.org/7.0.0/docs/LangRef.html#llvm-memset-intrinsics
Also fixes `memcpy` which has experienced the same change between 6 and 7.

LLVM 7 changed memset intrinsic signature, adjust it

---

llvmlite/ir/module.py
llvmlite/tests/test_ir.py

Reverts numba/llvmlite#460.  This seems to be causing issues with LLVM 8.

Revert "LLVM 7 changed memset intrinsic signature, adjust it"

---

setup.py

The recommended way to specify dependencies specific to a python
version is to use environment markers.
One downside of using if statements to specify dependencies is that it
can break applications using package managers like pipenv or poetry,
where the version of python running setup.py is not necessarily the
same verion of python being deployed.
It would certainly be fair to blame this on the package managers
themselves, but given the PEP and the fact that other packages have
solved this in the same way, I think it's worth fixing on this end.
See:
* https://www.python.org/dev/peps/pep-0508/#environment-markers
* https://github.com/hynek/argon2_cffi/issues/48
* https://github.com/hynek/argon2_cffi/commit/8eed81aa

Depend on enum34 using PEP 508 environment markers

---

ffi/dylib.cpp
ffi/executionengine.cpp
ffi/value.cpp
llvmlite/binding/ffi.py
llvmlite/binding/value.py

* All string returning C-API must return a `LLVMPY_CreateString` allocated string and the Python side must deallocate using `LLVMPY_DisposeString` or via `OutputString`.
* Added `ret_string` and `ret_bytes` to wrap the string return-value for cleanup.
* All string returning C-API must use `c_void_p` to avoid `ctypes` auto-conversion of `c_char_p` into a python string.

Fix leak on string returning APIs.

---

docs/source/user-guide/ir/values.rst

[The documentation for `ir.Constant`](https://llvmlite.readthedocs.io/en/latest/user-guide/ir/values.html#llvmlite.ir.Constant) erroneously nests some things under the `literal_struct()` classmethod.

Fix incorrect hierarchy in the documentation for ir.Constant.

---

docs/source/user-guide/ir/types.rst
llvmlite/ir/builder.py
llvmlite/ir/types.py
llvmlite/llvmpy/core.py
llvmlite/tests/test_ir.py
llvmlite/tests/test_valuerepr.py

In the style of Float and Double

Add Half-Precision Type

---

docs/source/conf.py
docs/source/user-guide/deprecation.rst
docs/source/user-guide/index.rst

As title. Follows LLVM change.

Deprecate the use of memset/memcpy with alias

---

llvmlite/ir/values.py
llvmlite/tests/test_binding.py

llvm will fail to parse the IR from a module if it contains a block with an "interesting" label (i.e. one which is not alphanumeric). These labels need to be quoted and escaped.
Rather than failing with a mysterious parse error, this allows llvmlite to accept the full space of strings as block labels.
(My use case is that the labels were b64 encoded hashes of AST structures. The b64 alphabet includes +, =, and /, which would randomly cause llvmlite to puke).

fix for block labels which contain "interesting" characters

---

CHANGE_LOG

Mark date for 0.30 release date in the changelog

---

CHANGE_LOG

Mark development of 0.31.0.
Merger will need to also tag the merging commit for v0.31.0dev0

Begin development of 0.31.0

---

docs/source/user-guide/ir/ir-builder.rst
llvmlite/ir/builder.py

Added `cttz` intrinsic to sphinx docs.
Should this be kept consistent with the doc-string? I think it would be useful if the doc-string had information about the flag as well.

Add cttz and ctlz to irbuilder docs.

---

docs/source/user-guide/deprecation.rst

Update deprecation docs with full deprecation of 5 arg memset/memcpy

---

docs/source/user-guide/ir/ir-builder.rst

The method in IRBuilder is called branch_indirect, not indirectbr (https://github.com/numba/llvmlite/blob/master/llvmlite/ir/builder.py#L803)

Miscalled method and missing parameter in the documentation

---

azure-pipelines.yml
ffi/build.py

The old ones will be removed 03/23/2020.
Allow Visual Studio 15 2017 as cmake generator.
Signed-off-by: Jan Vesely <jano.vesely@gmail.com>

azure-pipelines: Bump VM images.

---

.travis.yml

Use language:shell to avoid the overhead of setting up ruby.
Use new syntax keys.
Drop sudo: required.

travis: Cleanup

---

docs/source/admin-guide/install.rst

Going through documentation https://llvmlite.readthedocs.io/en/latest/admin-guide/install.html
was trying to do these steps:
```
0001-RuntimeDyld-Fix-a-bug-in-RuntimeDyld-loadObjectImpl-.patch: Fixes a bug relating to common symbol section size computation
0001-RuntimeDyld-Add-test-case-that-was-accidentally-left.patch: Test for the above patch
```
except the patches don't seem to be there:
```
$ find . -name *.patch
./conda-recipes/0001-Revert-Limit-size-of-non-GlobalValue-name.patch
./conda-recipes/D47188-svml-VF.patch
./conda-recipes/twine_cfg_undefined_behavior.patch
./conda-recipes/llvm-lto-static.patch
./conda-recipes/partial-testing.patch
```
Checking through `git log` seems it hasn't been there for a couple of months:
```
$ git log --all --full-history -1 -- …
```

update install docs

---

llvmlite/binding/targets.py
llvmlite/tests/test_binding.py

Return value of 0 indicates empty string/feature map:
https://github.com/llvm/llvm-project/blob/master/llvm/lib/Support/Host.cpp
Fixes: https://github.com/numba/llvmlite/issues/550
Signed-off-by: Jan Vesely <jano.vesely@gmail.com>

binding: Allow empty features list

---

docs/source/admin-guide/install.rst
docs/source/faqs.rst
docs/source/index.rst
ffi/build.py

Builds on: https://github.com/numba/llvmlite/pull/581
Adds override for LLVM version check, re-formats docs.
* Adds environment variable to remove LLVM version check.
* Reformats install guide doc:
* 80 char limit
* Move static linking prose to FAQ
* Add section on using unsupported LLVMs

Adds override for LLVM version check, re-formats docs.

---

CHANGE_LOG

as titled.
like https://github.com/numba/llvmlite/pull/586 but on release branch

Update changelog for 0.32.1 on release branch

---

conda-recipes/llvmlite/meta.yaml

Restore `VERSION_SUFFIX` accidentally removed in the llvm9 patch.

Fix meta.yaml

---

conda-recipes/0001-Revert-NVPTX-Use-atomicrmw-fadd-instead-of-intrinsic.patch
conda-recipes/0002-Revert-NVPTX-Remove-now-unused-atomic.load.add.f32-i.patch
conda-recipes/llvmdev/meta.yaml
conda-recipes/llvmdev_manylinux1/meta.yaml

The `llvm.nvvm.atomic.load.add` intrinsics were removed and `atomicrmw` is used in its place. The auto-upgrade of IR replaces any of the intrinsics with `atomicrmw`, which is a problem when sending the optimized IR to NVVM, which doesn't accept `atomicrmw`.
This commit adds patches to revert the removal of these intrinsics and corresponding auto-upgrade of the IR.

Fix CUDA with LLVM9

---

setup.py

As of version 0.32.0 (?) the lllvmlite package only supports Python 3.6
and beyond. As outlines in
https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires
- the appropriate line is added to the `setup.py` file to prevent `pip`
from installing the project on other Python versions.

add python_requires to setup.py

---

llvmlite/ir/builder.py
llvmlite/tests/test_ir.py

Small change that allows instructions to be removed from a Block after adding them. Includes test.

Allow instructions to be removed from blocks

---

CHANGE_LOG

Update changelog for 0.33.0

---

conda-recipes/llvmdev_manylinux1/build.sh

Fixes #601: add the missing GPU hosts to the wheel build for llvmdev.

add missing targets to wheel build

---

conda-recipes/intel-D47188-svml-VF.patch

Patch was updated to fix SVML calling convention issues uncovered by llvm 10. In previous versions of patch SVML calling convention was selected based on compilation settings. So if you try to call 256bit vector function from avx512 code function will be called with avx512 cc which is incorrect. To fix this SVML cc was separated into 3 different cc for 128, 256 and 512bit vector lengths which are selected based on actual input vector length.
CC @stuartarchibald

Update SVML patch

---

conda-recipes/llvmlite/meta.yaml
ffi/CMakeLists.txt
ffi/Makefile.linux
ffi/Makefile.osx
ffi/custom_passes.cpp
llvmlite/binding/passmanagers.py
llvmlite/tests/refprune_proto.py
llvmlite/tests/test_refprune.py

This adds a custom pass mainly for `numba` to prune redundant reference count.
Before merge, do these:

Implement reference count pruner LLVM pass

---

conda-recipes/llvmdev/meta.yaml
conda-recipes/llvmdev_manylinux2010/meta.yaml

The current version of `llvmdev` on `numba/label/main` is 10.0.1-1 -- as
this was build from the PR at:
https://github.com/numba/llvmlite/pull/636
To sync the state of the repository with the state of the build
artifacts, we must increment the llvmdev build number.

fix llvmdev build number

---

conda-recipes/llvmlite/meta.yaml

llvmlite will need to be built against the correct version and build
number of llvmdev. This pins that version number as part of the
`conda-recpie`.

pin to correct version of llvmdev

---

ffi/custom_passes.cpp
llvmlite/binding/passmanagers.py
llvmlite/tests/test_refprune.py

~~by rejecting visited nodes in fanout forward pass.~~
by limiting maximum visit count in fanout subgraph and avoiding revisiting into nodes that are known to always fail because of the CFG.

Fix refprune fanout_raise case getting stuck on large graphs

---

llvmlite/binding/common.py

Opening this PR to see what happens on CI.
This change was originally made in PR #53, but may no longer be required (and may cause issues with comments in IR that use non-latin1 characters).

Switch encoding to UTF-8 from latin1

---

docs/source/admin-guide/install.rst

Some missing whitespace and incorrect indentation caused the
installation instructuions to be malformed.
Before:
After:

fix rst syntax in install docs

---

README.rst

* Start with llvmlite, not llvmpy
* Move llvmpy comparison to section "Why llvmlite"
* Slight reformatting

slight rearrangement of intro

---

conda-recipes/llvmlite/meta.yaml

Use llvmdev build 2 -- which compared to build 1 is compiled on Visual Studio 16 2019 v141 on Windows, hence the change is for windows only.

use build 2 on windows

---

docs/source/user-guide/ir/ir-builder.rst
llvmlite/ir/builder.py
llvmlite/tests/test_ir.py

Whilst following our Compiler Construction course at VU University Amsterdam, we noticed the presence of the [`fneg` instruction in LLVM](https://llvm.org/docs/LangRef.html#fneg-instruction), which was absent in LLVMlite. 
Hence, we decided to make an attempt at adding this instruction.
We created a new decorator `_unop` for unary instructions and used that on `fneg`.

Added fneg instruction

---

conda-recipes/llvmlite/meta.yaml
ffi/CMakeLists.txt
ffi/build.py

This eases cross-compiling as seen in https://github.com/conda-forge/llvmlite-feedstock/pull/50

Support building with CMake on posix systems

---

setup.py

This adds code to limit the Python versions for which llvmlite can be installed. Code is adapted from the Numba project.

adapt Python version clamp from Numba

---

docs/source/glossary.rst
llvmlite/ir/values.py
llvmlite/tests/test_ir.py

Adding "alwaysinline" and "noinline" attributes to a function results in an error similar to the following when compiling with LLVM:
```
Attributes 'noinline and alwaysinline' are incompatible!
LLVM ERROR: Broken module found, compilation aborted!
```
and then the interpreter is killed. This PR prevents both attributes being added at the Python level, to prevent the above error message and termination.

Disallow alwaysinline and noinline on functions

---

ffi/CMakeLists.txt
ffi/Makefile.osx

Don't export LLVM symbols when linking statically

---

README.rst
azure-pipelines.yml
conda-recipes/llvmlite/meta.yaml
docs/source/contributing.rst
setup.py

Remove 3.6 support and include clamping the maximum Python version in the conda recipe as this had been omitted.

Remove 3.6 support

---

conda-recipes/llvmdev/conda_build_config.yaml
conda-recipes/llvmdev/meta.yaml
conda-recipes/llvmlite/conda_build_config.yaml
conda-recipes/llvmlite/meta.yaml
llvmlite/binding/ffi.py

As #758, with some updates to compiler choices and a bumped build number for llvmdev.

PR #758 continued. Ensure GCC7 is used on non-ARM platforms.

---

azure-pipelines.yml

As title. 16.04 is EOL since April 2021. See details here:
https://github.com/actions/virtual-environments/issues/3287

Update the Azure default linux image to Ubuntu 18.04

---

conda-recipes/llvmdev/conda_build_config.yaml
conda-recipes/llvmdev/meta.yaml
conda-recipes/llvmlite/conda_build_config.yaml
conda-recipes/llvmlite/meta.yaml

* PR #758 continued. Ensure GCC7 is used on non-ARM platforms.

Cherry-picks for 0.37.0

---

llvmlite/ir/values.py
llvmlite/tests/test_ir.py

See details and background in LLVM IR language reference:
https://llvm.org/docs/LangRef.html#ptrtoint-to-instruction

Adds _ConstOpMixin.ptrtoint to complement existing bitcast and inttoptr methods.

---

azure-pipelines.yml
buildscripts/azure/azure-linux-macos.yml
buildscripts/incremental/setup_conda_environment.sh
buildscripts/incremental/test.sh

This will ease the load on the testing runs. Also, it means, we can release for new versions of Python without having to wait for the availability of the doc packages.
cc: #769

don't build docs on every platform, only once

---

docs/source/user-guide/ir/ir-builder.rst
llvmlite/ir/builder.py
llvmlite/ir/instructions.py
llvmlite/tests/test_ir.py

This implements support for adding argument attributes at call
sites (`call`, `invoke`), which is necessary to actually emit
functions with attributes such as `sret` (for which leaving off
the attribute at the call site, i.e. specifying it only in the
function declaration, leads to miscompilations).
I opted for a fairly minimal implementation, just optionally
taking a dictionary of `AttributeSet`s in the constructur, as
the vast majority of call sites will not need to specify extra
attributes. Not sure whether a dictionary indexed by positional
indices is the most idiomatic solution…
I also added a commit removing the `tail` parameter from the
InvokeInstr constructor, as the tail call kind attributes aren't
actually supported on `invoke` by LLVM. Previously, that
parameter was just …

Implement minimal support for call-site argument attributes

---

conda-recipes/llvmdev/bld.bat
conda-recipes/llvmdev/build.sh
conda-recipes/llvmdev/meta.yaml
conda-recipes/llvmdev_manylinux2014/build.sh
conda-recipes/llvmdev_manylinux2014/meta.yaml

There is growing interest in using llvmlite as a cross-compiler to target RISC-V.  (See #785 and #775)  This adds the RISC-V target as well as all the default targets to both the llvmdev package build and the llvmdev_manylinux2014 package build for all platforms.  The increase in package size with this target should be ~30%.
(Note this is not adding RISC-V as a supported host platform for llvmlite, as that will require greater availability of RISC-V hardware running Linux, as well as a reasonable ecosystem of Python packages on that platform.)
Edit: Originally this PR only added RISC-V (at a size cost of 1.5%) but further discussion in #785 made it clear that we could add all the standard targets too.  Note that starting with LLVM 13, the standard targets include RISC-V and WebAssembly, …

Add RISC-V + all default targets to LLVM build

---

conda-recipes/llvmlite/meta.yaml

Testing the `llvmdev` build 4 produced via:
https://github.com/numba/llvmlite/pull/788

update to use LLVM 11.1.0 build 4

---

llvmlite/ir/values.py
llvmlite/tests/test_ir.py

Supersede to https://github.com/numba/numba/pull/7208
Fixes unicode encoding for LLVM debug metadata string.

Fix encoding of unicode string in metadata.

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md

These templates are similar to Numba's, but customised for llvmlite. The main aim in adding them is to direct questions and involved feature discussions toward the llvmlite section of the Numba discourse, rather than the creation of new issues.

Add issue templates based on those in Numba

---

docs/source/user-guide/ir/values.rst
llvmlite/ir/values.py
llvmlite/tests/test_ir.py

This continues PR #735, which I think was good to merge, save for the following required additions included in this PR:
- Merge master
- Resolve conflicts
- Document the new methods.
Documentation for the new methods follows the documentation of similar methods in the IR builder documentation (i.e. https://llvmlite.readthedocs.io/en/latest/user-guide/ir/ir-builder.html) - it is not new as such, but instead the wording was re-used for consistency.

Continue PR #735 (Add support for more constant expressions)

---

azure-pipelines.yml

macOS-10.14 and vs2017-win2016 are being deprecated by Azure CI.
This patch updates the images used to the oldest image that is
still supported.

Update Windows and OSX CI images.

---

docs/source/user-guide/binding/modules.rst
ffi/module.cpp
llvmlite/binding/module.py
llvmlite/tests/test_binding.py

This PR just adds a binding in `binding.ModuleRef` for llvm::Module::getSourceFileName

llvm::Module::GetSourceFileName

---

conda-recipes/llvmdev_manylinux2014/build.sh

Since we started building llvmdev with all backend target architectures
included (for binary wheels and binary conda packages) we noticed that
under Linux 32 we are not able to generate ppc64 code correctly. This is
viewed as a minor annoyance since it is a very unlikely use-case in
practice. Thus, we simply exclude the failing tests on Linux 32 so as to
be able to build and ship an llvmdev anyway.
For reference, the error messages looked like:
```
INFO - Failed Tests (2):
INFO - LLVM :: ExecutionEngine/RuntimeDyld/PowerPC/ppc64_elf.s
INFO - LLVM :: ExecutionEngine/RuntimeDyld/PowerPC/ppc64_reloc.s
```

Exclude ExecutionEngine tests on linux 32

---

docs/source/user-guide/deprecation.rst
llvmlite/llvmpy/__init__.py
llvmlite/llvmpy/core.py
llvmlite/llvmpy/passes.py

Add deprecation warnings to `llvmlite.llvmpy` and all of its submodules.

Deprecated `llvmlite.llvmpy`

---

docs/source/contributing.rst

DOC: Fix the syntax for the llvmlite discourse topic link.

---

.pre-commit-config.yaml
docs/source/contributing.rst

Include a clang-format pre-commit hook to ensure the code is formatted
automatically.

Add pre-commit hooks for clang-format

---

llvmlite/binding/passmanagers.py

Use `self.run` rather than the C binding for the `run_with_remarks` methods in
the passmanagers.

Delegate passmanager remarks methods

---

conda-recipes/llvmlite/meta.yaml

As part of the Anaconda build farm we also build and test llvmlite on
aarch64 using miniforge and conda-forge packages. The build has been
fine, until today, where we started seeing the following error messages:
```
/opt/conda/conda-bld/llvmlite_1661342292898/_build_env/bin/../lib/gcc/aarch64-conda-linux-gnu/9.5.0/../../../../aarch64-conda-linux-gnu/bin/ld: cannot find -lz
```
Upon inspection, it turns out that the zlib package had been excluded on
aarch64. The assumption is, that the package was installed as a
transient dependency and that this is no longer the case.
The resolution is to require it explicity during build.

Adding zlib as dependency for aarch64

---

azure-pipelines.yml

As title. vmImage macOS-10.15 is deprecated.

Move Azure to use macos-11.

---

docs/source/user-guide/ir/ir-builder.rst
llvmlite/ir/instructions.py
llvmlite/tests/test_ir.py

More background available in LLVM IR manual: https://llvm.org/docs/LangRef.html#call-instruction
API addition is backwards compatible with previous usage, so this doesn't break anyone.

Adds support for calling functions with 'tail', 'notail', or 'musttail' markers.

---

llvmlite/tests/test_setup.py
setup.py

Over at the conda-forge feedstock we [noticed](https://github.com/conda-forge/llvmlite-feedstock/pull/66#issuecomment-1292357510) that the build ignored the version guard since we didn't have `setuptools`/`packaging` installed.
Since we're only comparing "simple" versions and `sys.version_info` is a tuple already, we can simplify the logic by omitting version string parsing overall and just compare the tuples.
cc @jakirkham

Simplify setup.py Python version guard

---

azure-pipelines.yml

ubuntu-18.04 is deprecated and will have scheduled brownouts until fully unsupported on 2023-04-01. See for more details actions/runner-images#6002
Microsoft-hosted pipelines supports the 2 latest versions of macOS, Windows and Ubuntu. Now that ubuntu-22.04 is available, ubuntu-20.04 will become the oldest supported version as ubuntu-18.04 is being deprecated.
This bump of the ubuntu version in the azure pipelines CI was also completed in https://github.com/numba/numba/commit/af758e009a6ec3821e77cb9d92a7e3a7265a9cbc.

Upgrade to ubuntu-20.04 for azure pipeline CI

---

buildscripts/incremental/install_miniconda.sh

The Minconda installer seems to expect that `[[` can be used in all sh implementations, which is not necessarily the case (there are some discussions around this issue e.g. in https://github.com/conda/conda/issues/10431).
To attempt to work around this, we run the installer with bash instead.

Run Minconda install with bash

---

.flake8
llvmlite/ir/builder.py

Similar to numba/numba#8680, the config file needs updating for Flake8 6. One new error was detected, which is also corrected.

Fix flake8 config and style for flake8 6

---

.gitignore
.ycm_extra_conf.py

I've been working with this config locally for a long time, and I think it might be helpful to make more broadly available, as vim and YCM are a popular development combination. This PR has no effect on the code, the tests, or the build, but helps make llvmlite development on vim a smoother experience out-of-the-box for anyone using Vim + YCM, and working with Conda.
YouCompleteMe (https://github.com/ycm-core/YouCompleteMe) is a code-completion engine for vim. This PR adds a configuration file for it that enables it to understand the C++ FFI code in llvmlite by pointing to the correct include dirs (as long as one is working within a Conda environment), setting the relevant C++ standard, and ensuring that all header files are treated as C++.
Additionally, Vim swap files are added to the …

Add YouCompleteMe configuration file and ignore vim swap files

---

conda-recipes/llvm14-clear-gotoffsetmap.patch
conda-recipes/llvmdev/meta_llvm14.yaml

See:
- https://github.com/llvm/llvm-project/issues/61402
- https://github.com/numba/numba/issues/8738
Fixes numba/numba#8738.

llvmdev recipe: Add patch that clears GOTOffsetMap

---

README.rst
examples/lljit.py
ffi/CMakeLists.txt
ffi/Makefile.linux
ffi/Makefile.osx
ffi/orcjit.cpp
llvmlite/binding/__init__.py
llvmlite/binding/ffi.py
llvmlite/binding/orcjit.py
llvmlite/tests/test_binding.py

This mainly uses LLJIT through the C++ API avaiable in LLVM 14.
Create an API that allows creation of individual JITDylib as garbage-tracked Python objects so that life-cycle management of JITted code can be easily performed in Python.
Based-on: Graham Markall <gmarkall@nvidia.com>

Add ORCJITv2 support

---

llvmlite/binding/passmanagers.py

Fix #944. Add `.argtypes` to prevent errors in pypy.

---

ffi/targets.cpp
llvmlite/binding/passmanagers.py
llvmlite/tests/test_binding.py

Needed for https://github.com/numba/numba/issues/8898

Expose TargetLibraryInfo pass

---

llvmlite/tests/test_binding.py

Fix test by only running on x86 platforms.

Fix CI failing due to unsupported target triple on non-x86 platforms.

---

llvmlite/ir/types.py

Because the constructor is obsured, inference software really struggles with this particular field.

Add a type hint for `IntType.width`

---

llvmlite/tests/test_binding.py

LLVM considers `powerpc64le` and `ppc64le` synonymous but they aren't always normalized.
Closes #941

Handle PowerPC synonyms

---

conda-recipes/llvm14-svml.patch
conda-recipes/llvmdev/meta.yaml
conda-recipes/llvmlite/meta.yaml

Replaces the current LLVM 14 patch to add SVML support with https://github.com/Hardcode84/llvm-project/commit/9de32f5474f1f78990b399214bdbb6c21f8f098e
Closes #943

Update SVML patch for LLVM 14

---

llvmlite/binding/analysis.py
llvmlite/ir/instructions.py
llvmlite/ir/values.py
llvmlite/tests/test_ir.py

Some attributes now need type information. This preserves it.
Closes #946

Fix incorrect `byval` and other attributes on LLVM 14

---

CHANGE_LOG
conda-recipes/llvm14-svml.patch
conda-recipes/llvmdev/meta.yaml
conda-recipes/llvmlite/meta.yaml
llvmlite/binding/analysis.py
llvmlite/binding/passmanagers.py
llvmlite/ir/instructions.py
llvmlite/ir/values.py
llvmlite/tests/test_binding.py
llvmlite/tests/test_ir.py

Using the table at:
https://github.com/numba/llvmlite/issues/955#issue-1741319800
I put the following merge commits for the PRs that are to be backported in a file `0.40.1-cp`:
```
70f057b59a
e2dd7b0bb0
f2aa9a7f12
cb78125cd7
```
And then to cherry-pick them all at once:
```
cat 0.40.1-cp | xargs git cp -m1
```
The request for review is to ensure that the PRs required are correctly cherry-picked.

0.40.1 rel cherry pick

---

.github/ISSUE_TEMPLATE/first_rc_checklist.md
.github/ISSUE_TEMPLATE/sub_rc_checklist.md

Adding:
* Modifications of the change-log now happen on the release branch and are then cherry-picked back to main.
* Pre-tag-testing is now explicit.
* Post link to mastondon too.
* Minor synchronizations between the two checklists.

add various bullets to release checklists and sync

---

ffi/build.py
setup.py

LLVM is ported on the Hurd, and the Hurd has the same GNU toolchain that
is also generally used on Linux. Since build & the tests work fine,
apply/use some Linux build tweaks also on any GNU platform (including
the Hurd):
- the Linux `Makefile`
- `-fPIC` in `CXXFLAGS`

build: support building on GNU/Hurd

---

CHANGE_LOG

As per:
```
💣 zsh» git --no-pager log -1 --decorate --oneline
a4e5632677 (HEAD -> release0.40, tag: v0.40.1, origin/release0.40) Merge pull request #965 from esc/change_log_0.40.1
💣 zsh» git --no-pager log -1 --decorate --oneline main
2bfc31a009 (origin/main, origin/HEAD, main) Merge pull request #966 from pinotree/hurd
💣 zsh» git --no-pager diff main -- CHANGE_LOG
diff --git c/CHANGE_LOG w/CHANGE_LOG
index 57e08e4398..9a9206c01a 100644
--- c/CHANGE_LOG
+++ w/CHANGE_LOG
@@ -1,3 +1,18 @@
+v0.40.1 (June 21, 2023)
+-----------------------
+
+Pull-Requests:
+
+* PR `#945 <https://github.com/numba/llvmlite/pull/945>`_: Fix #944. Add `.argtypes` to prevent errors in pypy. (`Siu Kwan Lam <https://github.com/sklam>`_)
+* PR `#947 <https://github.com/numba/llvmlite/pull/947>`_: Update SVML patch …
```

update changelog on main for v0.40.1

---

conda-recipes/llvmlite/meta.yaml

`conda-build` will override this setting anyway, when building for Python 3.10 using `--python` like we do for llvmlite. It is effectively a no-op under these circumstances.

drop upper limit on Python for conda recipe

---

docs/source/user-guide/ir/ir-builder.rst
llvmlite/ir/builder.py
llvmlite/ir/instructions.py
llvmlite/tests/test_ir.py

Allow adding comments to generated IR

---

llvmlite/binding/orcjit.py
llvmlite/tests/test_binding.py

Add a `name` property with the OrcJIT library name in the tracker object.

Expose library name in OrcJIT tracker

---

.github/ISSUE_TEMPLATE/first_rc_checklist.md
.github/ISSUE_TEMPLATE/sub_rc_checklist.md

Update release checklist post 0.41.0rc1

---

.readthedocs.yaml
docs/environment.yml
docs/source/conf.py
readthedocs.yml
setup.py

adding RTD conf file V2 as per request

---

docs/source/user-guide/binding/optimization-passes.rst
ffi/passmanagers.cpp
llvmlite/binding/passmanagers.py
llvmlite/tests/test_binding.py

This PR adds the built-in instruction namer pass to `PassManager`. The `instnamer` pass is very useful to work with the Python bindings, especially when value names are discarded during compilation and `ValueRef.name` is empty.

Add Instruction Namer pass to PassManager

---

.readthedocs.yaml
docs/rtd-requirements.txt

As of recently, docs started failing:
https://readthedocs.org/projects/llvmlite/builds/22167903/
The error was:
```
Configuration error:
There is a programmable error in your configuration file:
Traceback (most recent call last):
File "/home/docs/checkouts/readthedocs.org/user_builds/llvmlite/envs/latest/lib/python3.11/site-packages/sphinx/config.py", line 358, in eval_config_file
exec(code, namespace)  # NoQA: S102
^^^^^^^^^^^^^^^^^^^^^
File "/home/docs/checkouts/readthedocs.org/user_builds/llvmlite/checkouts/latest/docs/source/conf.py", line 20, in <module>
import sphinx_rtd_theme
ModuleNotFoundError: No module named 'sphinx_rtd_theme'
```
This fixes that.

adding sphinx_rtd_theme to RTD build to fix build

---

llvmlite/tests/test_binding.py

Since OrcJIT is still experimental, and there seem to be some issues on platforms we don't regularly test on (e.g. Issue #1000), it seems prudent to simply skip the OrcJIT tests on non-x86 platforms.
It also deals with the lack of `Py_GetVersion()`, on PyPy, which causes an error running the tests - on PyPy `PyPy_GetVersion()` is used instead.
Fixes #1003.

Fix / workaround for OrcJIT blocking issues

---

conda-recipes/llvmlite/bld.bat
conda-recipes/llvmlite/meta.yaml
llvmlite/tests/test_binding.py

Don't duplicate testing. Remove old architectures and fix one regex typo in a test.

conda-recipe cleanups

---

llvmlite/binding/executionengine.py

It is used in various places in Numba. The comment here forces the reader to do a little pointless investigation, so remove it.

Remove suggestion that add_global_mapping() is unused

---

README.rst
azure-pipelines.yml
buildscripts/manylinux_2_17/README.md
conda-recipes/llvmlite/meta.yaml
docs/source/contributing.rst
setup.py

As titled,
This PR bumps the supported Python version to `3.9`.

Bump minimum supported Python version to 3.9

---

llvmlite/ir/instructions.py
llvmlite/ir/values.py
llvmlite/tests/test_ir.py

The PR adds a new attribute string to the set of known FunctionAttributes and CallInstrAttributes.
The convergent attribute is needed for certain function declarations and call instructions to generate correct SPMD code for OpenCL. Refer: https://llvm.org/docs/ConvergentOperations.html
Supersedes #1016 
PS: #1016 was opened from the `main` branch of my fork. I have moved the changes to a feature branch whose name better indicates the intent of these changes. I will close the PR #1016.

Add convergent as a supported FunctionAttribute and CallInstrAttribute.

---

CHANGE_LOG

Generated with:
```
python ../numba/maint/gitlog2changelog.py --token="<omitted>" --beginning="v0.41.0" --repo=numba/llvmlite --digits=4
```
and
```
python ../numba/maint/gitlog2changelog.py --token="<omitted>" --beginning="v0.41.0" --repo=numba/llvmlite --digits=3
```
run in the root of the llvmlite repo, checked out next to the Numba repo, and then merging the results, and eliminating duplicate entries that already appeared in the notes for 0.41.0 and 0.41.1

Add release notes for 0.42.0rc1

---

ffi/custom_passes.cpp
llvmlite/tests/test_refprune.py

I provide a potential fix for #1023 .
But I can't prove it in theory, maybe you can give a counterexample against this PR.
Will provide a test case for this.
fix #1023

skip `raise` basic blocks in `verifyFanoutBackward`

---

azure-pipelines.yml
buildscripts/azure/azure-linux-macos.yml
docs/source/conf.py
docs/source/index.rst

~Some PRs (e.g. #1046)  have problems with the docs because of the old Sphinx version CI is using, the latest available in the defaults channel being 5.0.2. This PR switches to using conda-forge to get later versions, so that features such as `:no-index:` can be used.~
~From the CI logs:~
```
sphinx-7.3.7               |     pyhd8ed1ab_0         1.3 MB  conda-forge
sphinx_rtd_theme-2.0.0     |     pyha770c72_0         2.5 MB  conda-forge
```
**Update**: The new approach in this PR is to remove the docs testing on Azure and enable nitpicky mode in the Sphinx config. Now:
- The RTD build is checking the same things as the Azure docs build was
- There is no inconsistency between Sphinx versions in docs testing (since RTD is only running one version of Sphinx)
I purposely broke a reference in …

Use RTD for all docs CI / testing (was: Try and get CI to use a newer Sphinx)

---

CHANGE_LOG

port changelog for 0.43.0 to main

---

ffi/targets.cpp
llvmlite/binding/targets.py
llvmlite/tests/test_binding.py

As titiled,
This PR aims to add a `llvm` based binding that uses the internal `Triple` object to partition the process triple string into it's respective parts.
Example:
```python
from llvmlite import binding
triple_string = binding.get_default_triple()
triple_string = "armv6hl-none-linux-gnueabi"
triple_parts = binding.get_triple_parts(triple_string)
print("Triple String:", triple_string)
print("Triple Parts:", triple_parts)
```

Added llvm based process triple partitioning

---

azure-pipelines.yml

macos-11 is deprecated and will be removed very soon.

Move Azure to use macos-12

---

ffi/newpassmanagers.cpp
llvmlite/tests/test_binding.py

This pattern in common in Numba which causes fpm to crash

Early exit from fpm.run() if called on function declarations

---

ffi/newpassmanagers.cpp
llvmlite/binding/ffi.py
llvmlite/binding/newpassmanagers.py
llvmlite/tests/test_binding.py

The new pass manager relies on PIC callbacks for deciding
if a function needs to be skipped for optimization when
compiled with 'optnone'.

Add instrumentation callback hook for new pass managers

---

conda-recipes/llvmdev/conda_build_config.yaml
conda-recipes/llvmdev/meta.yaml
conda-recipes/llvmlite/conda_build_config.yaml

Numba team build system for linux-aarch64 is being updated from Miniforge3 to miniconda3 based docker containers. `llvmlite` fails to compile from `main` with current recipe specification as compiler version 9 is not available for that architecture. We bump to 11 which is the default as referenced by:
https://github.com/AnacondaRecipes/aggregate/blob/master/conda_build_config.yaml
For reference, the error was:
```
The following packages are incompatible
├─ gcc_linux-aarch64 9.*  does not exist (perhaps a typo or a missing channel);
└─ gxx_linux-aarch64 9.*  does not exist (perhaps a typo or a missing channel).
```

bump compiler for linux-aarch64 to 11

---

docs/source/user-guide/binding/optimization-passes.rst
ffi/custom_passes.cpp
llvmlite/binding/newpassmanagers.py
llvmlite/binding/passmanagers.py
llvmlite/tests/test_binding.py
llvmlite/tests/test_refprune.py

Based on the changes introduced in #1042 by @modiking

Port refprune pass to NewPassManager

---

docs/source/conf.py

As title. This follows the instructions suggested in the warning message coming from RTD as noted in #1083, essentially, it removes the definition of html_theme_path which is set by calling the function in the title.
Fixes #1083

Fix RTD build, no need for get_html_theme_path().

---

llvmlite/binding/newpassmanagers.py

These missing descriptions might be causing refprune related windows tests failure after https://github.com/numba/numba/pull/9676

Add missing argtypes description for refprune pass related APIs

---

ffi/build.py

On windows, [HEAD](https://github.com/numba/llvmlite/commit/8cc8944f6234ca2eee0ecc817b834e5a7a27d2c5) is suffering from a segfault problem when running the testsuite. The problem is associated with the use of `-GL` flag on MSVC. The flag enables whole-program optimization. I cannot find any mentioning of this issue on LLVM issue tracker. 
The patch simply discard `-GL` from `CFLAGS` and `CXXFLAGS`. These environment variables can be set by user or build system (e.g. conda-build).
<details>
<summary>an ipython reproducer</summary>
```python
!python -m llvmlite.tests -vb
ct = 0
while _exit_code == 0:
!python -m llvmlite.tests -vb
ct += 1
print("count", ct)
```
This loops until it fails because it may takes several trial to reproduce. Usually within 3 runs. 
</details>

Add MSVC `-GL` workaround

---

docs/source/user-guide/ir/types.rst
docs/source/user-guide/ir/values.rst
llvmlite/ir/context.py
llvmlite/ir/types.py
llvmlite/ir/values.py
llvmlite/tests/test_binding.py
llvmlite/tests/test_ir.py

I found these helpful in a recent project. Not sure if there is a better way to do this. This is my first pull request so hopefully getting it right!
types.py: add get_element_offset to Type
values.py: add packed arg to literal_struct
context: add packed arg to get_identified_type
tests: add test cases

Add convenience func and args

---

CHANGE_LOG
README.rst
docs/source/conf.py

As titled this PR updates the date and llvm versioning for the `0.44.0cr1` release.

Updated date and llvm versioning for 0.44.0rc1

---

llvmlite/ir/builder.py
llvmlite/tests/test_ir.py

If ptr.type.is_opaque is True it doesn't need to have ptr.type.pointee attribute.
Add a unit test.

Fix store to opaque ptr

---

.github/workflows/llvmdev_win_builder.yml
conda-recipes/llvmdev_manylinux/bld.bat
conda-recipes/llvmdev_manylinux/conda_build_config.yaml
conda-recipes/llvmdev_manylinux/meta.yaml

(Based on #1104)
Users have reported error using the windows wheel for llvmlite on official CPython distribution (non-Anaconda builds). The error was due to `zlib.dll` dependency that is not available on the installed Python. 
This patch fixes the problem by using `llvmdev_manylinux` recipe which disabled zlib and zstd.
Note: With this patch, all wheel builds use `llvmdev_manylinux` recipe. The recipe folder should rename to `llvmdev_wheels` later. Don't want to do that now which will require changing more buildfarm scripts.
In addition, a GHA workflow is added to build the llvmdev for wheels. Example run: https://github.com/sklam/llvmlite/actions/runs/12186143333/job/33993961959

Fix Windows llvmdev build due to zlib linkage

---

ffi/passmanagers.cpp

Looking at the `unswitchLoop` function here: https://github.com/llvm/llvm-project/blob/fc3c4e1725273df3c701d57458373a50f215069b/llvm/lib/Transforms/Scalar/SimpleLoopUnswitch.cpp#L3561-L3563
It seems the pass shall skip the "NonTrivial" transformation when "OptimizeForSize" is set true.
For a reference, here's the use of `OptimizeForSize` in LLVM versions < 15:
https://github.com/llvm/llvm-project/blob/f28c006a5895fc0e329fe15fead81e37457cb1d1/llvm/lib/Transforms/Scalar/LoopUnswitch.cpp#L673-L675

Fix flag condition when creating SimpleLoopUnswitchLegacyPass

---

.github/workflows/llvmlite_win-64_conda_builder.yml

llvmlite win-64 conda builder GHA

---

.pre-commit-config.yaml
renovate.json
run_coverage.py
runtests.py
setup.py

While working on the Github Action workflow https://github.com/numba/llvmlite/pull/1144 I was relying on a local extended .pre-commit-config.yaml that I now share / propose for addition to the repo:
* Add actionlint hook which does lots of schema checking + shellcheck-ing (!) action step code
* Add check-jsonschema for pure schema checking of workflows and more
* Reducing the clang-format hook to `types_or: [c++, c, c#, cuda, metal]` as it would otherwise also format json files with lots of diff for the repo
* Adding flake8 hook: checks everything that is not excluded... so it includes new files to `./buildscripts/*` :)
* Fixed some .py file lints of files in the repo-root that are now not excluded anymore
* Adding yamlfmt to format the updated .pre-commit-config.yaml (applying to whole …

Extend pre-commit config

---

azure-pipelines.yml
buildscripts/incremental/test.sh
llvmlite/tests/test_binding.py

execute dist tests for linux-64 conda pkgs via Azure

---

llvmlite/ir/types.py
llvmlite/tests/test_ir.py

This fixes a few issues @stuartarchibald and I found with opaque pointers.

Opaque pointer fixes

---

docs/source/user-guide/binding/optimization-passes.rst
docs/source/user-guide/binding/pass_timings.rst
ffi/newpassmanagers.cpp
llvmlite/binding/ffi.py
llvmlite/binding/newpassmanagers.py
llvmlite/tests/test_binding.py

Enable LLVM Pass timings reporting with NewPassManager, to be used by Numba

Enable pass timings reporting with NewPassManager

---

.github/workflows/llvmlite_linux-64_conda_builder.yml

llvmlite_linux-64_conda_builder.yml

---

ffi/build.py
ffi/core.cpp
ffi/core.h
ffi/targets.cpp
ffi/type.cpp
llvmlite/__init__.py
llvmlite/binding/context.py
llvmlite/binding/targets.py
llvmlite/binding/typeref.py
llvmlite/ir/types.py
llvmlite/tests/test_binding.py
llvmlite/tests/test_ir.py
llvmlite/tests/test_refprune.py

At the LLVM level, going forward typed pointers are no longer supported.
This patch removes typed pointer support from the LLVM binding layer.
Initially, it also attempted to bump the LLVM version used to LLVM 16, but due to unrelated reasons with Anaconda, it seems it's easier to do that separately as a follow-up patch.

Drop binding layer typed pointer support.

---

llvmlite/ir/module.py
llvmlite/ir/values.py
llvmlite/tests/test_ir.py

The llvmlite debug metadata cache does not work as expected due to the encoding value using address of DIToken instance and serves as part of the key.
Solution is to extract the string value from the encoding object.
Since the DIToken class is designed to be a wrapper of enumeration value, e.g. the DW_* enumerations, that should appear bare in the emitted metadata, in this change, stringify DIToken is made to fix the problem.
This solves llvmlite issue https://github.com/numba/llvmlite/issues/1164

Fix the metadata deduplication

---

azure-pipelines.yml

As per https://github.com/actions/runner-images/issues/11101 -- 20.04 is being phased out.

bump Ubuntu to 24.04

---

azure-pipelines.yml
buildscripts/azure/azure-linux-macos.yml

As per https://github.com/numba/llvmlite/pull/1208#issuecomment-2839151540 this refactors the clang-format check to use a single job to execute it and uses clang-format-20 from conda-forge.

unify clang format check

---

.github/workflows/llvmdev_build.yml

```
ld: unsupported tapi file type '!tapi-tbd' in YAML file '/Applications/Xcode_15.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib/libSystem.tbd' for architecture x86_64
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```
The above error is mostly caused when using conda build under conda env on (intel-based) osx-64 systems.
It's because the newer toolchains are incompatible with conda build. 
To make this work, we download older toolchain and have conda build point to it using CONDA_BUILD_SYSROOT var.
```
--variants '{"CONDA_BUILD_SYSROOT": "/opt/MacOSX10.10.sdk"}'
```
Reference:
- [conda build doc](https://docs.conda.io/projects/conda-build/en/stable/resources/compiler-tools. …

fix llvmdev_build.yml to resolve toolchain incompatibility on osx-64

---

azure-pipelines.yml
buildscripts/azure/azure-windows.yml
buildscripts/incremental/build.cmd
ffi/build.py

To ensure CI functions without disruption, we need to migrate to newer Windows runner image - `windows-2025` from existing `windows-2019` .
This PR updates runner image for azure-pipelines.

azure-pipelines/win-2019 to 2025

---

buildscripts/manylinux/prepare_miniconda.sh

This PR adds CONDA_PLUGINS_AUTO_ACCEPT_TOS=1 to -
- GHA workflows that use conda environment and 
- scripts used to setup conda env for azure pipelines and on manylinux containers

set CONDA_PLUGINS_AUTO_ACCEPT_TOS to manylinux env setup script

---

ffi/newpassmanagers.cpp

This fixes the "pass timing" logic, that which reports on the time spent in LLVM internal passes, such that it doesn't print to STDOUT.

Fix pass timing logic to stop printing to stdout.

---

.github/workflows/llvmlite_linux-64_wheel_builder.yml
.github/workflows/llvmlite_linux-aarch64_wheel_builder.yml

updates job naming on linux GHA workflows to follow the same as others. eg.`linux-64-validate`
resolves https://github.com/numba/llvmlite/issues/1271

GHA/ standardize job names on workflows for linux builds

---

.github/workflows/llvmlite_linux-64_wheel_builder.yml
.github/workflows/llvmlite_linux-aarch64_wheel_builder.yml
.github/workflows/llvmlite_osx-64_wheel_builder.yml
.github/workflows/llvmlite_osx-arm64_wheel_builder.yml
.github/workflows/llvmlite_win-64_wheel_builder.yml
CHANGE_LOG
buildscripts/incremental/setup_conda_environment.cmd
buildscripts/incremental/setup_conda_environment.sh
buildscripts/manylinux/build_llvmlite.sh
conda-recipes/llvmdev_for_wheel/meta.yaml
docs/source/user-guide/deprecation.rst

This is the set of cherry-picks from the `release0.45` branch. The SHA1 sum and order was determined using:
```
zsh» git --no-pager log --oneline --merges `git merge-base main release0.45`..release0.45 | tac
89a5f22f16 Merge pull request #1268 from esc/release0.45
5e0c0977c7 Merge pull request #1269 from swap357/gha/add_llvmlite_sdist_wheel_workflow
bbe3985e6c Merge pull request #1276 from swap357/gha/fix_llvmdev_for_wheels_buildstring
222bfdc485 Merge pull request #1274 from swap357/gha/refactor_gha_job_names
52ad9b3187 Merge pull request #1278 from sklam/misc/update_deprecation_llvm20
47730fd806 Merge pull request #1282 from esc/release0.45
17c5a9843b Merge pull request #1289 from esc/gha/use_explicit_channel_pin_llvmdev_for_wheel
2d479c9ce4 Merge pull request #1287 from esc/release0.45 …
```

Cherry pick 0.45.0

---

.github/workflows/llvmlite_conda_builder.yml
.github/workflows/llvmlite_linux-64_wheel_builder.yml
.github/workflows/llvmlite_linux-aarch64_wheel_builder.yml
.github/workflows/llvmlite_osx-arm64_wheel_builder.yml
.github/workflows/llvmlite_win-64_wheel_builder.yml
buildscripts/github/llvmlite_evaluate.py
conda-recipes/llvmlite/meta.yaml

Adding support to build and test llvmlite with py3.14 on GHA CI.
- uses channel `ad-testing/label/py314` when using conda env
- for jobs using setup-python, we use `allow-prereleases: true` 
- skip using lief (`pip install -v lief`) on test job for python 3.14 (not yet supported)

GHA/ add Python 3.14 to CI
